### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by Jono72** [NitrofMtl/TimeOut#8]
Hi NitroMtl I apologies but I cant find away to contact you, are you able to tell me if your fork of the Websockets Server will work on my ESP8266 using Ethernet2 and w5500 I cannot seem to get any help from anyone and you seem to be the only person who may have solved the issue

Kind Regards

John

**Comment by NitrofMtl** [comment]
HI. I was able to use the server but not the client. I Have made a version to work with ethernet2 lib once but since then, I think Link004 lib have added support to the library long time ago.... I did not use it myself.

Regards.

Nitrof

**Comment by Jono72** [comment]
Thankyou your the only person who's has actually given me an answer, I have used Links2004 and the latest lib works fine with wifi but I could not get this to work with ESP82666 and Ethernet2 Lib, it just fails to connect, The lib was straight forward and easy to use, I only need server in any case. I have found a lib Websockets2_Generic however again I am struggling to get an answer to find out if this will work Ive been searching for weeks. apologies for contacting you on this thread but I could not find any way to contact you via your profile.

Thanks again John

**Comment by NitrofMtl** [comment]
ok.. quick look at [src](https://github.com/Links2004/arduinoWebSockets/tree/master/src)/WebSockets.h 
On line134:

` 

#if defined(ESP8266)
#include <ESP8266WiFi.h>
#elif defined(ESP32)
#include <WiFi.h>
#include <WiFiClientSecure.h>
#define SSL_AXTLS
#elif defined(ESP31B)
#include <ESP31BWiFi.h>
#else
#error "network type ESP8266 ASYNC only possible on the ESP mcu!"
#endif
`

This make the library, auto detect that you using ESP8266, and set the library to use the WIFI. 

One thing you could try is to use the [AtMega](https://github.com/Links2004/arduinoWebSockets/tree/ATmega) branch instead of the master. But you will still maybe have to modify it so that the WIFI do not have pryority over Ethernet.h...


Regards.

Nitrof

**Comment by Jono72** [comment]
Hi Nitrof

Thanks for your reply; seriously I have sled this question in a few forums now and to date no answer from anyone, I did attempt to modify the .h file as suggested and I can see how Network data type gets set if esp8266 is defined which of course it is, I tried to fix network so that it was set as Ethernet, I realized inn doing that the library then allows the standard Ethernet.h to be included (well that’s my understanding) this then seem to cause lots of compile errors because etehrnet2 is defined in my project, I tried to changes this with no success, I did some more searching but still in every instance where ESP8266 is defined it seems to assume that the ESps Wi-Fi is used, I want sure if this is because SSL is required for the web socket to function, I don’t want to take up your time but just wondered if you can send me the .h file you modified so as I can understand how  you managed to get the websocket server to work with Ethernet, like I said this is probably beyond my scope, but I am determined to find a solution and at the same time understand how this is done, It’s not about just getting it working but I would like to also understand why  and how.

thanks for your assistance sorry for pestering you.

Kind Regards

Jono

**Comment by NitrofMtl** [comment]
You should not use Ethernet2 library, it is deprecated. Use the latest Ethernet.h one that support all 3 wiznet chip. This is the most up to date.
Update it trough the library manager.
Then should not have include conflic anymore.

Regards.

Nitrof
